export const WORDS = {
  thuGon: 'Thu gọn',
  xemLichSu: 'Xem lịch sử',
  lichSu: 'Lịch sử',
  themMoi: 'Thêm mới',
  xoa: 'Xóa',
  xacNhanXoa: 'Xác nhận xóa',
  huyBo: 'Hủy bỏ',
  dongY: 'Đồng ý (Ctrl + S)',
  dongYWithKey: (key) => `Đồng ý (Ctrl + ${key})`,
  send: 'Gửi (Ctrl + S)',
  sendWithKey: (key) => `Gửi (Ctrl + ${key})`,
  sendApprove: 'Gửi duyệt (Ctrl + S)',
  sendApproveWithKey: (key) => `Gửi duyệt (Ctrl + ${key})`,
  stt: 'STT',
  thoiGian: 'Thời gian',
  nguoiThucHien: 'Người thực hiện',
  noiDung: 'Nội dung',
  moTa: 'Mô tả',
  ghiLai: 'Ghi lại',
  dong: 'Đóng',
  edit: 'Chỉnh sửa',
  close: 'Đóng (Esc)',
  delete: 'Đồng ý xóa (Ctrl + D)',
  recordAndClose: 'Ghi lại và Đóng',
  recordAndContinue: 'Ghi lại và Thêm tiếp',
  notiDeleteSuccess: 'Xóa thành công',
  notiEditSuccess: 'Sửa thành công',
  notiAddSuccess: 'Thêm thành công',
  manipulation: 'Thao tác',
  status: 'Trạng thái',
  using: 'Đang sử dụng',
  dontUsing: 'Không sử dụng',
  refuse: 'Từ chối',

  // Tai khoan
  logOut: 'Đăng xuất',

  // quan ly tai khoan, nguoi dung dang nhap
  watchInfo: 'Xem thông tin',
  accountInfo: 'Thông tin tài khoản',
  userInfo: 'Thông tin người dùng',
  accountName: 'Tên Tài khoản',
  taxCode: 'Mã số thuế',
  email: 'Email',
  phoneNumber: 'Số điện thoại',
  address: 'Địa chỉ',
  loginName: 'Tên đăng nhập',
  password: 'Mật khẩu',
  fullName: 'Tên đầy đủ',
  sdt: 'SĐT',
  roleGroup: 'Nhóm quyền',
  deptPosition: 'Phòng ban - Chức vụ',
  changePass: 'Đổi mật khẩu',
  historyAccountTitle: 'Xem lịch sử Tài khoản, Người dùng',
  changePassModalTitle: 'Đổi mật khẩu Người dùng',
  oldPass: 'Mật khẩu cũ',
  newPass: 'Mật khẩu mới',
  retypeNewPass: 'Nhập lại mật khẩu mới',
  newPassHelp: 'Mật khẩu tối thiểu 6 ký tự, tối đa 20 ký tự',
  editAccountTitle: 'Chỉnh sửa thông tin Tài khoản',
  editUserTitle: 'Chỉnh sửa thông tin Người dùng',

  // WEC information
  informationWEC: 'Thông tin WEC',
  source: 'Nguồn',
  type: 'Loại',
  accountPreprocessing: 'Tài khoản XL trước',
  accountHandling: 'Tài khoản XL',
  contentWEC: 'Nội dung WEC',
  createDate: 'Ngày tạo',
  duration: 'Thời hạn',
  remainingTerm: 'Thời hạn còn lại',
  numberReceived: 'Số lần nhận',
  processingLogBefore: 'Nhật ký xử lý trước',
  processDateBefore: 'Ngày xử lý trước',
  emptyListWec: 'Không có cảnh báo nào !',
  residual: 'Còn lại ',

  // Quan ly uy quyen
  confirmDelegacy: 'Chấp nhận được Ủy quyền',
}
